### ISSUE TITLE
the hyparameters of hoi match loss

### ISSUE THREAD

**Issue by SISTMrL** [bbepoch/HoiTransformer#11]
![image](https://user-images.githubusercontent.com/47938053/122423742-ba3a8580-cfc0-11eb-8a8f-be572c834576.png)
hello, in your paper, the beta1 and beta2 is 2 and 1 leads to best results, it shows classication loss is important than bbox loss. but in your code in this picture, the default self.cost_class is 1, self.cost_bbox is 5, self.cost_giou is 2, why do you set these parameters, thanks!

**Comment by bbepoch** [comment]
This work is based on DETR, so we didn't change the original hyper-parameters. And on the base of object detector, we study the relative importance of classification and regression for HOI.

The cost showed in the code is not the right version, we are re-organizing the code.

BTW, we are supporting dataset HOI-A and V-COCO now.
