### ISSUE TITLE
about number of object categories

### ISSUE THREAD

**Issue by JackWhite-rwx** [bbepoch/HoiTransformer#12]
Excuse me!

It's a grate job, Tanks for what you contribute.

The paper say that HICO-DET has 80 objects,but  num_classes is 91 in /models/hoitr.py   345 lines.Why set it like this？

And could you tell me how to get  'hico_train_retag_hoitr.odgt' from hico-det datasets' file?

thank you very much!

**Comment by bbepoch** [comment]
we have just updated the repo, supporting V-COCO and HOI-A,
1. Because the 80-category-coco ids is incontinuity, ranging from 1 to 90. We set it to 91 for simplicity though there are some 'blank' index.
2. we introduced the annotation format in readme.

**Comment by JackWhite-rwx** [comment]
OK,Thanks for your answer!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bbepoch/HoiTransformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bbepoch/HoiTransformer] about number of object categories (#12)





 
we have just updated the repo, supporting V-COCO and HOI-A,
  
Because the 80-category-coco ids is incontinuity, ranging from 1 to 90. We set it to 91 for simplicity though there are some 'blank' index.
 
we introduced the annotation format in readme.

**Comment by csEylLee** [comment]
> we have just updated the repo, supporting V-COCO and HOI-A,
> 
> 1. Because the 80-category-coco ids is incontinuity, ranging from 1 to 90. We set it to 91 for simplicity though there are some 'blank' indices.
> 2. we introduced the annotation format in readme.

为什么是91而不是90呢？+1是因为空集吗？但是在最后分类层的时候又加了一次1，输出维度变成92了。
