### ISSUE TITLE
Person activity without object detection 

### ISSUE THREAD

**Issue by abhigoku10** [bbepoch/HoiTransformer#21]
@bbepoch hi thanks for sharing the code base great work, but i had one query, currently when i tested the model for some scenes like an only person running on a beach without any other object present there is no detections/activity in the output, is there any way i can get results like people walking , fighting, waving without depending on the object present in the scene

Thanks in advance

**Comment by bbepoch** [comment]
Of course, but you need to train a new model. 

There are many ways to do so, but the core idea is to **properly define your positive samples**.

Method 1: In pedestrian detection framework, the output is (box regression, human confidence), you can add one external output which indicates the human activity of the current human, namely outputs (box regression, human confidence, **activity confidence**).

Method 2: In this HOI Transformer end-to-end framework, you can define a new kind of HOI instance, like (human box, human confidence, object box, object confidence, **has object or not**). In this way, human activities with or without objects can be modeled in a unified framework.

**Comment by abhigoku10** [comment]
@bbepoch  THanks for the response , 
In Method 1 when you say "add one external output " it means to have another branch which gives activity confidence ? what is activity confidence to be included . can you please elaborate

**Comment by bbepoch** [comment]
Yes, another branch. To make it easier, another channel is enough
