### ISSUE TITLE
The results on HICO-DET is much better than paper. Curious about what's the key modifications?

### ISSUE THREAD

**Issue by zyong812** [bbepoch/HoiTransformer#30]
Thanks for the nice work! By reading your paper and code, I find something very confusing. 
Why the performance on VCOCO is similar to the paper, while much better than paper for HICO-DET? What's the key factor for such results?

**Comment by bbepoch** [comment]
We changed the post processing code, as a result, it boosted the performance on HICO-DET.
Post processing matters !!!

In this new version of code, the hyper-parameters and post processing code are completely the same for HICO-DET, V-COCO and HOI-A. So the result on V-COCO became about 1.0 mAP lower than the result reported in paper.
