### ISSUE TITLE
viz_hoi_result draw object box retangle incorrect position

### ISSUE THREAD

**Issue by mac-tieu** [bbepoch/HoiTransformer#31]
Hi there,

I trained model with a small dataset (person raising hand) without any problem. But when I run test_on_images to test prediction, it drawed incorrect object box position (attached image). Could you help me figure out what I've done incorrectly?

![img_1-ch01_20210331111737_0013 jpg_000000](https://user-images.githubusercontent.com/55741046/127958248-ec507596-9dd5-4d1f-9357-315c74832016.jpg)

Best regards,
MT.

**Comment by bbepoch** [comment]
Be careful not to mistake h and w

**Comment by mac-tieu** [comment]
Thanks a lot for your help! 

After finetuned DETR checkpoint before training HoiTransformer (using the same dataset), the test results are as expected. 
![img_1-ch01_20210331111737_0013 jpg_000001](https://user-images.githubusercontent.com/55741046/128165308-9f10a9fc-6a5b-4266-a939-1907c5337752.jpg)

Again, thanks for your works!

**Comment by bbepoch** [comment]
Great work!

**Comment by sunny-liulyw** [comment]
how to make our own dataset?
