### ISSUE TITLE
vcoco annotation

### ISSUE THREAD

**Issue by SISTMrL** [bbepoch/HoiTransformer#32]
hello, in your repo, the vcoco_test.odgt contains the 4953 images, but the ori vcoco test set contains above 5000 images, the vcoco performance should be test on 4953 images or 5000+ images? looking forward to your reply, thanks!

**Comment by bbepoch** [comment]
Really? we have not realized it. There must be some mistake when processing the dataset.

Of course it should be tested on the whole 5000+ images. 

The performance would be better when tested on 5000+ images.

Thanks

**Comment by SISTMrL** [comment]
@bbepoch the experiment accomplished on vcoco in your project, did you use this odgt format vcoco dataset?
