### ISSUE TITLE
自己的数据集应用hico格式和odgt 训练出错

### ISSUE THREAD

**Issue by mytk2012** [bbepoch/HoiTransformer#35]
**错误信息:**/opt/conda/conda-bld/pytorch_1591914895884/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: operator(): block: [0,0,0], thread: [62,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1591914895884/work/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=59 : device-side assert triggered
**py文件**hoitr.py文件num_humans 是不是代表有多少人？那hico数据集中每张图的人员数量不是固定值，这个参数怎么设置呢？

**Comment by bbepoch** [comment]
num_humans保持不变就行

**Comment by mytk2012** [comment]
运行成功了，但是想问下，为什么人员类别一定要设置为1，输出的human_out_prob是三列？
