### ISSUE TITLE
some questions about the result

### ISSUE THREAD

**Issue by fengliqiu** [bbepoch/HoiTransformer#43]
Hi,
Thanks for your great work. #Sorry to bother you. I noticed some differences between the repo and the paper.

In repo:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/47531370/150900703-b79ecaa3-3b26-4b43-a503-1dbda37df846.png">

In paper:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/47531370/150900775-fe937bd6-0d49-4724-adc8-c00bb7d5421b.png">

Maybe I overlooked something else, but i really can not understand the reasons. Could you please explain this？

**Comment by bbepoch** [comment]
Mainly because there was an bug when writing the paper, but some time later, it was fixed.

**Comment by fengliqiu** [comment]
Thank you for your reply. I understand it. Thanks!
