### ISSUE TITLE
A question about your V-COCO dataset.

### ISSUE THREAD

**Issue by Vancause** [bbepoch/HoiTransformer#44]
First of all, thanks for sharing the source code of the paper (End-to-End Human Object Interaction Detection with HOI Transformer) which was accepted in CVPR. I have a question about your V-COCO dataset. The original V-coco dataset consists of 5,400 images in the trainval dataset and 4946 images in the test set. But I download your retag dataset from google drive which consists of 4971 images in trainval set and 4539 images in the test set. 

May I ask whether I downloaded the wrong data or the data has been processed especially? 

I look forward to receiving your reply.

**Comment by bbepoch** [comment]
The data you downloaded is right, and we were looking for the reason why the number is incorrect. 
We will reply soon the moment we find it.

BTW, this may be the reason why the performance on V-COCO is not that high.

**Comment by hwuidue** [comment]
Thanks for your great work! I found that there is not test_vcoco_final.pkl in vcoco's eval project . could you give me some help? thank you
