### ISSUE TITLE
A question about odgt annotations.

### ISSUE THREAD

**Issue by Zhanyi0923** [bbepoch/HoiTransformer#45]
Hello Author,  thank you for your great work!
Recently, I tried to use HoiTransformer to train my own dataset. I have some questions about the odgt annotations.
Taking HICO_train2015_00000001.jpg for example, my questions are as follows:

1. In the original HICO annotation of this picture, there was only one pair of boxes for motorcycle and person. However, in the ODGT annotation, I found that this picture had more than one pair of boxes for motorcycle and person(but there is only one person and motorcycle in the pic), and the coordinates of each box were not the same, but the difference was not significant. I did not understand this point. (why are the coordinates of boxes of the same person or motorbike is different).

2. The coordinate of the person box in this picture in the hico annotations is [207,32,426,299], but the coordinates in odgt annotations is [207,32,220,268]. My understanding is that in hico annotations, the coordinates are the coordinates of the upper-left and lower-right points of the box, whereas in your odgt annotation, the coordinates are the upper-left points and the length and width of the box. Although this explanation seems reasonable, according to this understanding, the length and width of the person box should be [426-207=219,299-32=267], but it is [220,268] in ODGT annotations.  Please tell me why.

Thanks again for your excellent work! Your answer will be of great help to me.
Looking forward to your reply!

**Comment by Jilinlin** [comment]
Hello, sorry to bother you. I'm also trying to use HoiTransformer to train my own data set. I would like to ask you how you made the data set in HOI format?

**Comment by Jilinlin** [comment]
> 

Hello, sorry to bother you. I'm also trying to use HoiTransformer to train my own data set. I would like to ask you how you made the data set in HOI format?

**Comment by Zhanyi0923** [comment]
是说如何标注还是改成文中odgt的格式？



At 2022-07-10 21:56:44, "冀琳" ***@***.***> wrote:

Hello, sorry to bother you. I'm also trying to use HoiTransformer to train my own data set. I would like to ask you how you made the data set in HOI format?

**Comment by bbepoch** [comment]
It is very easy for you to make ODGT training file,
![image](https://user-images.githubusercontent.com/45303299/179441089-1dccfbd1-469f-4861-a275-09432a6554f8.png)

**Comment by bbepoch** [comment]
> 2\. The coordinate of the person box in this picture in the hico annotations is [207,32,426,299], but the coordinates in odgt annotations is [207,32,220,268]. My understanding is that in hico annotations, the coordinates are the coordinates of the upper-left and lower-right points of the box, whereas in your odgt annotation, the coordinates are the upper-left points and the length and width of the box. Although this explanation seems reasonable, according to this understanding, the length and width of the person box should be [426-207=219,299-32=267], but it is [220,268] in ODGT annotations.  Please tell me why.

In my understanding,
width = x2-x1+1
height = y2-y1+1

**Comment by bbepoch** [comment]
> 1. In the original HICO annotation of this picture, there was only one pair of boxes for motorcycle and person. However, in the ODGT annotation, I found that this picture had more than one pair of boxes for motorcycle and person(but there is only one person and motorcycle in the pic), and the coordinates of each box were not the same, but the difference was not significant. I did not understand this point. (why are the coordinates of boxes of the same person or motorbike is different).

We converted the data from original HICO-DET annotations, it sure has duplicate boxes.
