### ISSUE TITLE
training on swin-b backbone

### ISSUE THREAD

**Issue by OBVIOUSDAWN** [bbepoch/HoiTransformer#46]
I find some swin-b code in repositories and tried to train this model on swin-b.But i find the train loss convergence at 70 and it cant drop with any training.Can you share how to train this model on swin-b or teach me if there anything code need to complete in this repositories that i will tried to complete this code.I would be appreciate for your reponse,thank you so much.

**Comment by bbepoch** [comment]
You are supposed to train a swin-b backbone DETR at first, and then load it as the initialization to train an HOI detector
