### ISSUE TITLE
Question about the training and evaluation code on VCOCO dataset?

### ISSUE THREAD

**Issue by GWwangshuo** [bbepoch/HoiTransformer#7]
Thanks for your nice work. Could you also provide the source code for training and evaluating on VCOCO dataset since it takes too long for the training on the HICO-Det dataset? Thanks a lot.

**Comment by GWwangshuo** [comment]
Besides, could you also provide the source code of creating annotation and eval files (`hico_test_retag_hoitr.odgt, hico_trainval_retag_hoitr.odgt, corre_hico.npy, nid2fname.json, test_hico.json, trainval_hico.json`)?

**Comment by bbepoch** [comment]
You know, recently we are busy, so, probably after the submission of camera-ready materials. Thanks

**Comment by bbepoch** [comment]
Sorry for this late, 
1, we have just pushed the code, including V-COCO, HOI-A.
2, we have provided annotation files for all the benchmarks, so you don't have to know how to convert, just use it. And we are preparing a visulazition tool for this format.
