### ISSUE TITLE
Question about training parameters.

### ISSUE THREAD

**Issue by kaenkogashi** [bbepoch/HoiTransformer#8]
Thanks for your nice work!  I know --epochs=250 for HICO-Det dataset. How many epochs about VCOCO dataset you used?  100 epochs or less than 100 epochs? And how about other parameters, like --lr_drop=200 and --batch_size=2 , are they as same as HICO-Det do? Thanks a lot.

**Comment by bbepoch** [comment]
For VCOCO, --epochs=150 --lr_drop=120 --batch_size=2. It will be about 1 mAP lower if they are set the same with HICO-DET.
