### ISSUE TITLE
Why do we need self.human_cls_embed?

### ISSUE THREAD

**Issue by JacobYuan7** [bbepoch/HoiTransformer#9]
I don't quite understand the **self.human_cls_embed** in **class HoiTR**. Why do we need to classify the human box? What do the 2 classes stand for?

**Comment by bbepoch** [comment]
In fact, only one class (index 1), it stands for the confidence of human box. For HICO-DET or V-COCO dataset, it can be ignored. but for real world application, it can be used to suppress a large number of false positives by thresholding
